/**
 * @file StaffForm.tsx
 * @description Presentador atómico (Dumb Component) para el alta y edición de personal (CRUD).
 * Optimizado bajo el MANIFIESTO DE NIVELACIÓN:
 * - Gobernación Semántica: 100% adaptado a la paleta pms-surface, border-pms-border y text-pms-text.
 * - SSoT de Identidad: Email autogenerado por eventos reactivos sin efectos secundarios (react-hooks/set-state-in-effect resuelto).
 * - Saneamiento de Ficha de Salud: Remoción absoluta de campos médicos obsoletos.
 * - Saneamiento de Linter: Eliminadas importaciones de iconos huérfanos y resuelto ts(2304) importando toast de Sonner.
 */

import React, { useState } from 'react';
import { parsePhoneNumberFromString } from 'libphonenumber-js';
import { Mail, HeartPulse, UserCheck } from 'lucide-react'; // ✅ Saneamiento: Removidos iconos sin uso
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { toast } from 'sonner'; // ✅ Saneamiento: Importado para resolver ts(2304)
import { cn } from '@/lib/utils';
import { type StaffMember } from './index';

interface StaffFormProps {
  /** Datos iniciales en caso de estar en modo edición. Nulo para modo creación. */
  initialData: StaffMember | null;
  /** Estado de guardado de la transacción de red */
  isSaving: boolean;
  /** Callback activado al enviar datos sanitizados */
  onSubmit: (data: {
    first_name: string;
    middle_name: string | null;
    paternal_last_name: string;
    maternal_last_name: string | null;
    email: string;
    role: 'housekeeper' | 'receptionist' | 'admin';
    country: string;
    state_code: string;
    phone: string;
    emergency_contact_name: string;
    emergency_contact_phone: string;
  }) => Promise<void>;
  /** Callback opcional para cancelar la edición o registro */
  onCancel?: () => void;
  /** Función de traducción del componente padre */
  t: (key: string, options?: Record<string, string | number>) => string;
}

export const StaffForm: React.FC<StaffFormProps> = ({
  initialData,
  isSaving,
  onSubmit,
  onCancel,
  t,
}) => {
  // Estados locales controlados
  const [firstName, setFirstName] = useState('');
  const [middleName, setMiddleName] = useState('');
  const [paternalLastName, setPaternalLastName] = useState('');
  const [maternalLastName, setMaternalLastName] = useState('');
  const [email, setEmail] = useState('');
  const [isEmailManual, setIsEmailManual] = useState(false); // Flag para apagar el autocompletado al editar manualmente
  
  const [phone, setPhone] = useState('');
  const [country, setCountry] = useState('Brasil');
  const [stateCode, setStateCode] = useState('SC');
  const [role, setRole] = useState<'housekeeper' | 'receptionist' | 'admin'>('housekeeper');

  // Contacto de Emergencia
  const [emergencyContactName, setEmergencyContactName] = useState('');
  const [emergencyContactPhone, setEmergencyContactPhone] = useState('');

  // Sincronización limpia de estados al abrir/editar (Patrón de React 19)
  const [prevInitialData, setPrevInitialData] = useState<StaffMember | null>(undefined);
  if (initialData !== prevInitialData) {
    setPrevInitialData(initialData);
    if (initialData) {
      setFirstName(initialData.first_name);
      setMiddleName(initialData.middle_name || '');
      setPaternalLastName(initialData.paternal_last_name);
      setMaternalLastName(initialData.maternal_last_name || '');
      setEmail(initialData.email);
      setIsEmailManual(true); // Bloquea autocompletado en edición
      setPhone(initialData.phone);
      setCountry(initialData.country);
      setStateCode(initialData.state_code);
      setRole(initialData.role as 'housekeeper' | 'receptionist' | 'admin');
      setEmergencyContactName(initialData.emergency_contact_name);
      setEmergencyContactPhone(initialData.emergency_contact_phone);
    } else {
      setFirstName(''); setMiddleName(''); setPaternalLastName(''); setMaternalLastName('');
      setEmail(''); setIsEmailManual(false); setPhone(''); setCountry('Brasil'); setStateCode('SC');
      setRole('housekeeper'); setEmergencyContactName(''); setEmergencyContactPhone('');
    }
  }

  // ============================================================================
  // ⚡ ALGORITMO DE NORMALIZACIÓN REACTIVO DIRIGIDO POR EVENTOS (Cero useEffect)
  // ============================================================================
  const syncAutogeneratedEmail = (first: string, last: string) => {
    if (initialData || isEmailManual) return;
    if (!first.trim() && !last.trim()) {
      setEmail('');
      return;
    }
    const cleanFirst = first.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9.]/g, '');
    const cleanLast = last.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9.]/g, '');
    setEmail(`${cleanFirst}.${cleanLast}@beachcanasvieiras.com`);
  };

  const handleFirstNameChange = (val: string) => {
    setFirstName(val);
    syncAutogeneratedEmail(val, paternalLastName);
  };

  const handleLastNameChange = (val: string) => {
    setPaternalLastName(val);
    syncAutogeneratedEmail(firstName, val);
  };

  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!firstName.trim() || !paternalLastName.trim() || !email.trim() || !phone.trim() || !emergencyContactName.trim() || !emergencyContactPhone.trim()) {
      toast.error('Por favor, preencha todos os campos obrigatórios (*).');
      return;
    }

    // Validaciones telefónicas internacionales con libphonenumber-js
    const normalizedPhone = phone.trim().startsWith('+') ? phone.trim() : `+${phone.trim()}`;
    const parsedPhone = parsePhoneNumberFromString(normalizedPhone);
    if (!parsedPhone || !parsedPhone.isValid()) {
      toast.error('Número de telefone do funcionário inválido.');
      return;
    }

    const normalizedEmerg = emergencyContactPhone.trim().startsWith('+') ? emergencyContactPhone.trim() : `+${emergencyContactPhone.trim()}`;
    const parsedEmerg = parsePhoneNumberFromString(normalizedEmerg);
    if (!parsedEmerg || !parsedEmerg.isValid()) {
      toast.error('Número do contato de emergência inválido.');
      return;
    }

    await onSubmit({
      first_name: firstName.trim(),
      middle_name: middleName.trim() || null,
      paternal_last_name: paternalLastName.trim(),
      maternal_last_name: maternalLastName.trim() || null,
      email: email.trim().toLowerCase(),
      role,
      country,
      state_code: stateCode.trim(),
      phone: parsedPhone.format('E.164'),
      emergency_contact_name: emergencyContactName.trim(),
      emergency_contact_phone: parsedEmerg.format('E.164')
    });
  };

  const rolesList: { role: 'housekeeper' | 'receptionist' | 'admin'; label: string }[] = [
    { role: 'housekeeper', label: 'Limpieza' },
    { role: 'receptionist', label: 'Recepção' },
    { role: 'admin', label: 'Administrador' }
  ];

  return (
    <form onSubmit={handleFormSubmit} className="space-y-5 text-pms-text">
      
      {/* 🚀 E-mail Corporativo Autogerado / Editable */}
      <div className="p-4 bg-pms-accent/10 border border-pms-accent/20 rounded-2xl flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-2 text-pms-accent">
          <Mail size={16} />
          <span className="text-[10px] font-body font-bold uppercase tracking-widest">
            {t('form.email_auto_label', { defaultValue: 'E-mail de Login Registrado (Editável):' })}
          </span>
        </div>
        <div className="relative flex-1 sm:max-w-xs focus-within:ring-2 focus-within:ring-pms-accent/20 rounded-lg">
          <input
            type="email"
            required
            value={email}
            onChange={(e) => {
              setEmail(e.target.value);
              setIsEmailManual(true); // Desactiva autocompletado para dar control absoluto al administrador
            }}
            placeholder="nome.sobrenome@beachcanasvieiras.com"
            disabled={isSaving}
            className="w-full bg-pms-surface-high border border-pms-border rounded-lg px-3 py-2 font-mono text-xs text-pms-text focus:border-pms-accent outline-none text-right placeholder:text-pms-text-muted"
          />
        </div>
      </div>

      {/* Grid: Nombres */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="p-3.5 rounded-2xl border border-pms-border bg-pms-surface-high focus-within:border-pms-accent focus-within:bg-pms-surface transition-all">
          <label className="block text-[8px] font-body font-bold text-pms-text-muted uppercase tracking-widest mb-1">
            {t('form.first_name', { defaultValue: 'Primeiro Nome *' })}
          </label>
          <input type="text" required value={firstName} onChange={(e) => handleFirstNameChange(e.target.value)} placeholder="Ex: Bernardo" disabled={isSaving} className="w-full bg-transparent border-none p-0 focus:ring-0 font-body text-xs text-pms-text outline-none" />
        </div>
        <div className="p-3.5 rounded-2xl border border-pms-border bg-pms-surface-high focus-within:border-pms-accent focus-within:bg-pms-surface transition-all">
          <label className="block text-[8px] font-body font-bold text-pms-text-muted uppercase tracking-widest mb-1">
            {t('form.middle_name', { defaultValue: 'Nome do Meio (Opcional)' })}
          </label>
          <input type="text" value={middleName} onChange={(e) => setMiddleName(e.target.value)} placeholder="Ex: José" disabled={isSaving} className="w-full bg-transparent border-none p-0 focus:ring-0 font-body text-xs text-pms-text outline-none" />
        </div>
      </div>

      {/* Grid: Apellidos */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="p-3.5 rounded-2xl border border-pms-border bg-pms-surface-high focus-within:border-pms-accent focus-within:bg-pms-surface transition-all">
          <label className="block text-[8px] font-body font-bold text-pms-text-muted uppercase tracking-widest mb-1">
            {t('form.paternal_last_name', { defaultValue: 'Sobrenome Paterno *' })}
          </label>
          <input type="text" required value={paternalLastName} onChange={(e) => handleLastNameChange(e.target.value)} placeholder="Ex: Martinez" disabled={isSaving} className="w-full bg-transparent border-none p-0 focus:ring-0 font-body text-xs text-pms-text outline-none" />
        </div>
        <div className="p-3.5 rounded-2xl border border-pms-border bg-pms-surface-high focus-within:border-pms-accent focus-within:bg-pms-surface transition-all">
          <label className="block text-[8px] font-body font-bold text-pms-text-muted uppercase tracking-widest mb-1">
            {t('form.maternal_last_name', { defaultValue: 'Sobrenome Materno (Opcional)' })}
          </label>
          <input type="text" value={maternalLastName} onChange={(e) => setMaternalLastName(e.target.value)} placeholder="Ex: Silva" disabled={isSaving} className="w-full bg-transparent border-none p-0 focus:ring-0 font-body text-xs text-pms-text outline-none" />
        </div>
      </div>

      {/* Grid: Contacto y Residencia */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="p-3.5 rounded-2xl border border-pms-border bg-pms-surface-high focus-within:border-pms-accent focus-within:bg-pms-surface transition-all">
          <label className="block text-[8px] font-body font-bold text-pms-text-muted uppercase tracking-widest mb-1">
            {t('form.phone', { defaultValue: 'Celular / WhatsApp *' })}
          </label>
          <input type="tel" required value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Ex: +5548998126650" disabled={isSaving} className="w-full bg-transparent border-none p-0 focus:ring-0 font-body text-xs text-pms-text outline-none" />
        </div>
        <div className="flex gap-4">
          <div className="flex-1 p-3.5 rounded-2xl border border-pms-border bg-pms-surface-high focus-within:border-pms-accent transition-all">
            <label className="block text-[8px] font-body font-bold text-pms-text-muted uppercase tracking-widest mb-1">
              {t('form.country', { defaultValue: 'País' })}
            </label>
            <select value={country} onChange={(e) => setCountry(e.target.value)} disabled={isSaving} className="w-full bg-transparent border-none p-0 font-body text-xs text-pms-text outline-none cursor-pointer">
              <option value="Brasil">Brasil</option>
              <option value="Argentina">Argentina</option>
            </select>
          </div>
          <div className="w-24 p-3.5 rounded-2xl border border-pms-border bg-pms-surface-high focus-within:border-pms-accent transition-all">
            <label className="block text-[8px] font-body font-bold text-pms-text-muted uppercase tracking-widest mb-1">
              {t('form.state_code', { defaultValue: 'UF' })}
            </label>
            <input type="text" required maxLength={2} value={stateCode} onChange={(e) => setStateCode(e.target.value)} placeholder="SC" disabled={isSaving} className="w-full bg-transparent border-none p-0 uppercase text-center font-body text-xs text-pms-text outline-none" />
          </div>
        </div>
      </div>

      {/* Ficha de Emergencia */}
      <div className="p-5 rounded-3xl border border-pms-border bg-pms-surface-high/20 space-y-4">
        <div className="flex items-center gap-2 border-b border-pms-border pb-2.5">
          <HeartPulse size={16} className="text-pms-accent" />
          <span className="text-[10px] font-body font-bold text-pms-text uppercase tracking-widest">
            {t('form.emergency_title', { defaultValue: 'Contato de Emergência Operacional' })}
          </span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="p-3 bg-pms-surface border border-pms-border rounded-2xl focus-within:border-pms-accent/40">
            <label className="block text-[8px] font-bold text-pms-text-muted uppercase tracking-widest mb-1">
              {t('form.emergency_name', { defaultValue: 'Nome Completo *' })}
            </label>
            <input type="text" required value={emergencyContactName} onChange={(e) => setEmergencyContactName(e.target.value)} placeholder="Ex: María Silva" disabled={isSaving} className="w-full bg-transparent border-none p-0 text-xs text-pms-text outline-none" />
          </div>
          <div className="p-3 bg-pms-surface border border-pms-border rounded-2xl focus-within:border-pms-accent/40">
            <label className="block text-[8px] font-bold text-pms-text-muted uppercase tracking-widest mb-1">
              {t('form.emergency_phone', { defaultValue: 'Celular *' })}
            </label>
            <input type="tel" required value={emergencyContactPhone} onChange={(e) => setEmergencyContactPhone(e.target.value)} placeholder="Ex: +5548999999999" disabled={isSaving} className="w-full bg-transparent border-none p-0 text-xs text-pms-text outline-none" />
          </div>
        </div>
      </div>

      {/* Selector de Rol */}
      <div className="p-4 rounded-3xl border border-pms-border bg-pms-surface-high">
        <label className="block text-[8px] font-bold text-pms-text-muted uppercase tracking-widest mb-3">
          {t('form.role_title', { defaultValue: 'Cargo do Funcionário *' })}
        </label>
        <div className="grid grid-cols-3 gap-2">
          {rolesList.map((item) => (
            <button key={item.role} type="button" onClick={() => setRole(item.role)} disabled={isSaving} className={cn("h-11 rounded-xl border text-xs font-semibold cursor-pointer transition-all border-pms-border bg-pms-surface", role === item.role ? "bg-pms-accent text-pms-accent-foreground border-pms-accent shadow-md" : "text-pms-text-muted hover:border-pms-accent/40")}>
              {item.label}
            </button>
          ))}
        </div>
      </div>

      {/* Botones de Control */}
      <div className="flex gap-3 pt-3">
        {onCancel && (
          <Button type="button" onClick={onCancel} disabled={isSaving} className="flex-1 h-14 bg-pms-surface-high border border-pms-border text-pms-text rounded-full text-xs font-bold uppercase tracking-widest transition-all active:scale-[0.98]">
            Cancelar
          </Button>
        )}
        <Button type="submit" disabled={isSaving} className="flex-1 h-14 bg-pms-accent text-pms-accent-foreground hover:opacity-90 rounded-full text-xs font-bold uppercase tracking-widest flex items-center justify-center gap-2 shadow-md transition-all active:scale-[0.98] border-none">
          {isSaving ? <Spinner className="w-5 h-5 text-pms-accent-foreground" /> : <><UserCheck size={16} /> {initialData ? t('form.edit_button', { defaultValue: 'Salvar Alterações' }) : t('form.submit_button', { defaultValue: 'Registrar' })}</>}
        </Button>
      </div>

    </form>
  );
};